import type { Metadata } from 'next';

/**
 * Site-wide SEO settings.
 *
 * The public address is https://zajel.com. Every canonical link, og:url,
 * sitemap entry, robots.txt line and structured-data URL is built from it.
 * NEXT_PUBLIC_SITE_URL overrides it (e.g. for a staging domain); `next dev`
 * uses localhost so local links keep working.
 */
const PRODUCTION_URL = 'https://zajel.com';

function resolveSiteUrl(): string {
  const explicit = process.env.NEXT_PUBLIC_SITE_URL;
  if (explicit) return explicit.replace(/\/+$/, '');
  if (process.env.NODE_ENV === 'development') return 'http://localhost:3000';
  return PRODUCTION_URL;
}

export const SITE = {
  url: resolveSiteUrl(),
  name: 'Zajel',
  legalName: 'ZAJEL Courier Services',
  tagline: 'Courier, Freight & Logistics in the UAE',
  description:
    'Zajel delivers same-day courier, international shipping, air, sea and land freight, customs clearance and warehousing across the UAE and to 195 countries.',
  locale: 'en_AE',
  /** Generated by app/opengraph-image.tsx. */
  ogImage: { url: '/opengraph-image', width: 1200, height: 630, alt: 'Zajel | Courier, Freight & Logistics in the UAE' },
  foundingYear: '2008',
  phone: '+971600531111',
  email: 'info@zajel.ae',
  logo: '/logo.svg',
  addresses: [
    { locality: 'Dubai', country: 'AE' },
    { locality: 'Abu Dhabi', country: 'AE' },
  ],
  // Add the real profile URLs here (Instagram, LinkedIn, X, YouTube) once they are final.
  socialProfiles: [] as string[],
} as const;

interface PageSeo {
  /** Page title without the brand; " | Zajel" is added automatically. */
  title: string;
  description: string;
  /** Route path, e.g. '/air-freight'. Used for the canonical link and social previews. */
  path: string;
  /** Keep the page out of search results (thin, private or per-user pages). */
  noIndex?: boolean;
}

/** Builds consistent metadata for a page: title, description, canonical and social previews. */
export function pageMetadata({ title, description, path, noIndex }: PageSeo): Metadata {
  const fullTitle = title.endsWith(`| ${SITE.name}`) ? title : `${title} | ${SITE.name}`;
  return {
    title: { absolute: fullTitle },
    description,
    alternates: { canonical: path },
    openGraph: {
      type: 'website',
      siteName: SITE.name,
      locale: SITE.locale,
      url: path,
      title: fullTitle,
      description,
      // A page's openGraph replaces the site default, so the preview image is set here too.
      images: [SITE.ogImage],
    },
    twitter: { card: 'summary_large_image', title: fullTitle, description, images: [SITE.ogImage.url] },
    ...(noIndex ? { robots: { index: false, follow: true } } : {}),
  };
}
