import type { Shipment } from './types';

export const MOCK_SHIPMENT: Shipment = {
  trackingNumber: 'ZAJEL123456789',
  status: 'delivered',
  statusLabel: 'Delivered',
  sender: {
    name: 'ABC Trading L.L.C',
    addressLine: 'Dubai Marina, Dubai, UAE',
    phone: '+971 50 123 4567',
  },
  receiver: {
    name: 'Amaneyyy',
    addressLine: 'Dubai Marina, Dubai, UAE',
    phone: '+971 50 123 4567',
  },
  origin: 'Dubai Marina, Dubai, UAE',
  destination: 'Dubai Marina, Dubai, UAE',
  service: {
    serviceType: 'ZAJEL Express',
    weightKg: 2.5,
    pieces: 1,
  },
  deliveredAtLabel: 'Jan 5, 2026 at 02:30 PM',
  deliveredOnLabel: 'Jan 6, 2026',
  routeMapImageUrl: '/images/tracking/route-map-placeholder.png',
  timeline: [
    {
      status: 'created',
      label: 'Created',
      location: 'Dubai Marina, Dubai',
      datetime: '2026-01-05T09:00:00',
      note: 'Shipment created and booking confirmed',
      done: true,
    },
    {
      status: 'picked_up',
      label: 'Picked Up',
      location: 'Dubai Marina',
      datetime: '2026-01-05T10:30:00',
      note: 'Package picked up from sender location',
      done: true,
    },
    {
      status: 'at_hub',
      label: 'At Hub',
      location: 'ZAJEL Hub – Dubai',
      datetime: '2026-01-05T11:45:00',
      note: 'Arrived at sorting facility',
      done: true,
    },
    {
      status: 'in_transit',
      label: 'In Transit',
      location: 'En route to Abu Dhabi',
      datetime: '2026-01-05T13:00:00',
      note: 'Package in transit to destination city',
      done: true,
    },
    {
      status: 'out_for_delivery',
      label: 'Out for Delivery',
      location: 'Abu Dhabi',
      datetime: '2026-01-05T14:15:00',
      note: 'Out for delivery to recipient address',
      done: true,
    },
    {
      status: 'delivered',
      label: 'Delivered',
      location: 'Downtown, Abu Dhabi',
      datetime: '2026-01-05T15:45:00',
      note: 'Successfully delivered to recipient',
      done: true,
    },
  ],
  proofOfDelivery: {
    receivedBy: 'John Smith',
    deliveryDate: 'January 5, 2026',
    deliveryTime: '03:45 PM',
    deliveryNotes: 'Package delivered to reception desk as per instructions',
    photoUrl: '/images/tracking/pod-placeholder.png',
  },
};
